# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/API"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "composer"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "terraform"
    directory: "/Terraform/AzureContainerRegistry"
    schedule:
      interval: "daily"
          
  - package-ecosystem: "terraform"
    directory: "/Terraform/ClusterAKS"
    schedule:
      interval: "daily"
          
  - package-ecosystem: "terraform"
    directory: "/Terraform/Pipeline-GH"
    schedule:
      interval: "daily"
    
        - package-ecosystem: "terraform"
    directory: "/Terraform/StorageAccount"
    schedule:
      interval: "daily"
